---
  - name: Docker pull {{ broker_image }}
    docker_image:
      name: "{{ broker_image }}"

  - name: Docker pull {{ etcd_image }}
    docker_image:
      name: "{{ etcd_image }}"

  - name: Curling ansible-service-broker-all.yaml
    get_url:
      url: https://raw.githubusercontent.com/openshift/ansible-service-broker/master/ansible-service-broker-all.yaml
      dest: /tmp/deploy-ansible-service-broker-all.yaml.j2

  - name: Setting facts for rendering ansible-service-broker-all.yaml template
    set_fact:
      dockerhub_pass: "{{ dockerhub_user_password }}"
      dockerhub_user: "{{ dockerhub_user_name }}"
      dockerhub_org: "{{ dockerhub_org_name }}"
      openshift_pass: "{{ cluster_user_password }}"
      openshift_user: "{{ cluster_user }}"
      openshift_target: "{{ openshift_url }}"

  - name: Rendering deploy-ansible-service-broker-all.yaml
    template:
      src: /tmp/deploy-ansible-service-broker-all.yaml.j2
      dest: /tmp/deploy-ansible-service-broker-all.yaml
      owner: "{{ ansible_env.USER }}"
      mode: 0644

  - name: Create ansible-service-broker-all
    shell: "{{ oc_cmd }} create -f /tmp/deploy-ansible-service-broker-all.yaml"

  - name: Switch project to ansible-service-broker
    shell: "{{ oc_cmd }} project ansible-service-broker"

  - name: Waiting 10 minutes for ASB pod
    action:
      shell "{{ oc_cmd }}" get pods | grep -iEm1 "asb.*?running" | grep -v deploy
    register: wait_for_asb_pod
    until: wait_for_asb_pod.rc == 0
    retries: 60
    delay: 10

  - name: Waiting 10 minutes for ASB etcd pod
    action:
      shell "{{ oc_cmd }}" get pods | grep -iEm1 "etcd.*?running" | grep -v deploy
    register: wait_for_asb_etcd_pod
    until: wait_for_asb_etcd_pod.rc == 0
    retries: 60
    delay: 10

  - name: Get route for ansible-service-broker
    shell: "'{{ oc_cmd }}' get routes | grep ansible-service-broker | awk '{print $2}'"
    register: result_get_route_asb
    retries: 6
    delay: 10

  - set_fact:
      ansible_service_broker_route:  "{{ result_get_route_asb.stdout }}"

  - name: Trigger ASB bootstrap to load APBs
    uri:
      url: http://{{ ansible_service_broker_route }}/v2/bootstrap
      method: POST
    register: response
    until: response|success and response.json and response.json.spec_count
    retries: 3
    delay: 30

  - name: Creating /tmp/ansible_service_broker.yaml
    template:
      src: ansible_service_broker.yaml.j2
      dest: /tmp/ansible_service_broker.yaml
      owner: "{{ ansible_env.USER }}"
      mode: 0644
    register: ansible_service_broker_template

  - name: Create Broker resource in Service Catalog
    shell: "{{ kubectl_cmd }} --kubeconfig={{ ansible_env.HOME }}/.kube/service-catalog.config create -f /tmp/ansible_service_broker.yaml"
